server:
  port: 8080
  address: 0.0.0.0
#添加数据源
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://139.9.225.131:3551/quant?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: Her88Man88Cloud88
    druid:
      initial-size: 5
      min-idle: 10
      max-active: 20
      max-wait: 60000
      min-evictable-idle-time-millis: 6000
      time-between-eviction-runs-millis: 3000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      filters: stat,wall
      use-global-data-source-stat: true
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  application:
    name: qt-admin
  redis:
    database: 0
    host: 139.9.225.131
    port: 3550
    password: hermanredis
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 15000
  mail:
    host: smtp.qq.com #发送邮件服务器
    username: 252424391@qq.com #QQ邮箱 请换自己的邮箱谢谢
    password: vzerswmamuaecadg #客户端授权码
    protocol: smtp #发送邮件协议
    properties.mail.smtp.auth: true
    properties.mail.smtp.port: 465 #端口号465或587
    properties.mail.display.sendmail: quant #可以任意
    properties.mail.display.sendname: quant Email #可以任意
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8
    from: 252424391@qq.com #与上面的username保持一致
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_ZONE_HOST:0.0.0.0}:${EUREKA_ZONE_PORT:8761}/eureka/
mybatis-plus:
  mapper-locations: classpath*:mapper/*Mapper.xml

vpnproxy:
  enable: false
  ip: 127.0.0.1
  port: 1088
